const eventData = [
  {
    title: 'Lagos Tech Conference 2024',
    category: 'Technology',
    price: 50000,
    description:
      'A premier gathering of tech innovators, entrepreneurs, and investors in Nigeria.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Landmark Event Centre',
    location: 'Plot 2 & 3 Water Corporation Road, Victoria Island, Lagos',
    totalTickets: 1000,
    startDateTime: '2024-03-15T09:00:00',
    endDateTime: '2024-03-17T17:00:00',
  },
  {
    title: 'Abuja Food Festival',
    category: 'Food & Drink',
    price: 10000,
    description:
      'Experience the diverse culinary landscape of Nigeria with food stalls, cooking demos, and live music.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Eagle Square',
    location: 'Abuja, FCT',
    totalTickets: 5000,
    startDateTime: '2024-04-20T12:00:00',
    endDateTime: '2024-04-21T20:00:00',
  },
  {
    title: 'Port Harcourt Music Concert',
    category: 'Music',
    price: 25000,
    description: 'Featuring top Nigerian musicians and upcoming artists.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Yakubu Gowon Stadium',
    location: 'Port Harcourt, Rivers State',
    totalTickets: 8000,
    startDateTime: '2024-05-10T19:00:00',
    endDateTime: '2024-05-11T02:00:00',
  },
  {
    title: 'Creative Writing Workshop',
    category: 'Literature',
    price: 0,
    description: 'A free workshop for aspiring writers to hone their skills.',
    image: '/assets/images/image1.jpg',
    isFree: true,
    venue: 'University of Ibadan',
    location: 'Ibadan, Oyo State',
    totalTickets: 200,
    startDateTime: '2024-06-05T10:00:00',
    endDateTime: '2024-06-05T16:00:00',
  },
  {
    title: 'Nollywood Film Premiere',
    category: 'Film',
    price: 15000,
    description: 'Exclusive premiere of a new Nollywood blockbuster.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Genesis Cinemas, Lekki',
    location: 'Lekki Phase 1, Lagos',
    totalTickets: 300,
    startDateTime: '2024-07-12T18:00:00',
    endDateTime: '2024-07-12T21:00:00',
  },
  {
    title: 'Abuja Fashion Week',
    category: 'Fashion',
    price: 30000,
    description: 'Showcasing the latest trends in Nigerian fashion.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'International Conference Centre',
    location: 'Abuja, FCT',
    totalTickets: 1500,
    startDateTime: '2024-08-02T10:00:00',
    endDateTime: '2024-08-04T19:00:00',
  },
  {
    title: 'Lagos Art Exhibition',
    category: 'Art',
    price: 5000,
    description:
      'Featuring contemporary Nigerian art from emerging and established artists.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Nike Art Gallery',
    location: 'Lekki, Lagos',
    totalTickets: 500,
    startDateTime: '2024-09-15T11:00:00',
    endDateTime: '2024-09-16T17:00:00',
  },
  {
    title: 'Ibadan Book Fair',
    category: 'Literature',
    price: 0,
    description:
      'A celebration of books and reading with author talks, book signings, and workshops.',
    image: '/assets/images/image1.jpg',
    isFree: true,
    venue: 'The Polytechnic, Ibadan',
    location: 'Ibadan, Oyo State',
    totalTickets: 1000,
    startDateTime: '2024-10-26T09:00:00',
    endDateTime: '2024-10-28T18:00:00',
  },
  {
    title: 'Calabar Carnival After Party',
    category: 'Entertainment',
    price: 10000,
    description: 'The official after-party for the famous Calabar Carnival.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'U. J. Esuene Stadium',
    location: 'Calabar, Cross River State',
    totalTickets: 10000,
    startDateTime: '2024-12-27T21:00:00',
    endDateTime: '2024-12-28T04:00:00',
  },
  {
    title: 'Kaduna Agricultural Fair',
    category: 'Agriculture',
    price: 2000,
    description:
      'Showcasing agricultural products, technologies, and innovations in Northern Nigeria.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Kaduna International Trade Fair Complex',
    location: 'Kaduna, Kaduna State',
    totalTickets: 2000,
    startDateTime: '2025-01-10T09:00:00',
    endDateTime: '2025-01-12T17:00:00',
  },
  {
    title: 'Benin Cultural Festival',
    category: 'Culture',
    price: 0,
    description:
      'A celebration of the rich cultural heritage of the Benin Kingdom.',
    image: '/assets/images/image1.jpg',
    isFree: true,
    venue: 'Oba Akenzua Cultural Centre',
    location: 'Benin City, Edo State',
    totalTickets: 1500,
    startDateTime: '2025-02-14T10:00:00',
    endDateTime: '2025-02-16T18:00:00',
  },
  {
    title: 'Owerri Gospel Concert',
    category: 'Music',
    price: 5000,
    description:
      'An evening of uplifting gospel music with renowned gospel artists.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Dan Anyiam Stadium',
    location: 'Owerri, Imo State',
    totalTickets: 5000,
    startDateTime: '2025-03-22T17:00:00',
    endDateTime: '2025-03-22T22:00:00',
  },
  {
    title: 'Sokoto Trade Fair',
    category: 'Business',
    price: 3000,
    description:
      'A platform for businesses to showcase their products and services in Sokoto State.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Sokoto State Trade Fair Complex',
    location: 'Sokoto, Sokoto State',
    totalTickets: 1000,
    startDateTime: '2025-04-05T09:00:00',
    endDateTime: '2025-04-07T17:00:00',
  },

  {
    title: 'Lagos Tech Conference 2024',
    category: 'Technology',
    price: 50000,
    description:
      'A premier gathering of tech innovators, entrepreneurs, and investors in Nigeria.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Landmark Event Centre',
    location: 'Plot 2 & 3 Water Corporation Road, Victoria Island, Lagos',
    totalTickets: 1000,
    startDateTime: '2024-03-15T09:00:00',
    endDateTime: '2024-03-17T17:00:00',
  },
  {
    title: 'Abuja Food Festival',
    category: 'Food & Drink',
    price: 10000,
    description:
      'Experience the diverse culinary landscape of Nigeria with food stalls, cooking demos, and live music.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Eagle Square',
    location: 'Abuja, FCT',
    totalTickets: 5000,
    startDateTime: '2024-04-20T12:00:00',
    endDateTime: '2024-04-21T20:00:00',
  },
  {
    title: 'Port Harcourt Music Concert',
    category: 'Music',
    price: 25000,
    description: 'Featuring top Nigerian musicians and upcoming artists.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Yakubu Gowon Stadium',
    location: 'Port Harcourt, Rivers State',
    totalTickets: 8000,
    startDateTime: '2024-05-10T19:00:00',
    endDateTime: '2024-05-11T02:00:00',
  },
  {
    title: 'Creative Writing Workshop',
    category: 'Literature',
    price: 0,
    description: 'A free workshop for aspiring writers to hone their skills.',
    image: '/assets/images/image1.jpg',
    isFree: true,
    venue: 'University of Ibadan',
    location: 'Ibadan, Oyo State',
    totalTickets: 200,
    startDateTime: '2024-06-05T10:00:00',
    endDateTime: '2024-06-05T16:00:00',
  },
  {
    title: 'Nollywood Film Premiere',
    category: 'Film',
    price: 15000,
    description: 'Exclusive premiere of a new Nollywood blockbuster.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Genesis Cinemas, Lekki',
    location: 'Lekki Phase 1, Lagos',
    totalTickets: 300,
    startDateTime: '2024-07-12T18:00:00',
    endDateTime: '2024-07-12T21:00:00',
  },
  {
    title: 'Abuja Fashion Week',
    category: 'Fashion',
    price: 30000,
    description: 'Showcasing the latest trends in Nigerian fashion.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'International Conference Centre',
    location: 'Abuja, FCT',
    totalTickets: 1500,
    startDateTime: '2024-08-02T10:00:00',
    endDateTime: '2024-08-04T19:00:00',
  },
  {
    title: 'Lagos Art Exhibition',
    category: 'Art',
    price: 5000,
    description:
      'Featuring contemporary Nigerian art from emerging and established artists.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Nike Art Gallery',
    location: 'Lekki, Lagos',
    totalTickets: 500,
    startDateTime: '2024-09-15T11:00:00',
    endDateTime: '2024-09-16T17:00:00',
  },
  {
    title: 'Ibadan Book Fair',
    category: 'Literature',
    price: 0,
    description:
      'A celebration of books and reading with author talks, book signings, and workshops.',
    image: '/assets/images/image1.jpg',
    isFree: true,
    venue: 'The Polytechnic, Ibadan',
    location: 'Ibadan, Oyo State',
    totalTickets: 1000,
    startDateTime: '2024-10-26T09:00:00',
    endDateTime: '2024-10-28T18:00:00',
  },
  {
    title: 'Calabar Carnival After Party',
    category: 'Entertainment',
    price: 10000,
    description: 'The official after-party for the famous Calabar Carnival.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'U. J. Esuene Stadium',
    location: 'Calabar, Cross River State',
    totalTickets: 10000,
    startDateTime: '2024-12-27T21:00:00',
    endDateTime: '2024-12-28T04:00:00',
  },
  {
    title: 'Kaduna Agricultural Fair',
    category: 'Agriculture',
    price: 2000,
    description:
      'Showcasing agricultural products, technologies, and innovations in Northern Nigeria.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Kaduna International Trade Fair Complex',
    location: 'Kaduna, Kaduna State',
    totalTickets: 2000,
    startDateTime: '2025-01-10T09:00:00',
    endDateTime: '2025-01-12T17:00:00',
  },
  {
    title: 'Benin Cultural Festival',
    category: 'Culture',
    price: 0,
    description:
      'A celebration of the rich cultural heritage of the Benin Kingdom.',
    image: '/assets/images/image1.jpg',
    isFree: true,
    venue: 'Oba Akenzua Cultural Centre',
    location: 'Benin City, Edo State',
    totalTickets: 1500,
    startDateTime: '2025-02-14T10:00:00',
    endDateTime: '2025-02-16T18:00:00',
  },
  {
    title: 'Owerri Gospel Concert',
    category: 'Music',
    price: 5000,
    description:
      'An evening of uplifting gospel music with renowned gospel artists.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Dan Anyiam Stadium',
    location: 'Owerri, Imo State',
    totalTickets: 5000,
    startDateTime: '2025-03-22T17:00:00',
    endDateTime: '2025-03-22T22:00:00',
  },
  {
    title: 'Sokoto Trade Fair',
    category: 'Business',
    price: 3000,
    description:
      'A platform for businesses to showcase their products and services in Sokoto State.',
    image: '/assets/images/image1.jpg',
    isFree: false,
    venue: 'Sokoto State Trade Fair Complex',
    location: 'Sokoto, Sokoto State',
    totalTickets: 1000,
    startDateTime: '2025-04-05T09:00:00',
    endDateTime: '2025-04-07T17:00:00',
  },
];
