export const events = [
  {
    _id: '1',
    title: 'Lagos Tech Summit',
    description: 'A premier gathering of tech enthusiasts in Lagos.',
    location: 'Landmark Event Center',
    city: 'Lagos',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/lagos-tech-summit.jpg',
    coverImageUrl: 'https://example.com/images/lagos-tech-cover.jpg',
    startDateTime: new Date('2025-03-15T09:00:00'),
    endDateTime: new Date('2025-03-15T17:00:00'),
    isFree: false,
    url: 'https://lagostechsummit.ng',
    category: { _id: 'c1', name: 'Technology' },
    organizer: { _id: 'o1', firstName: 'John', lastName: 'Doe' },
    tags: ['tech', 'summit', 'innovation'],
    attendeeLimit: 500,
    ratings: [],
    featured: true,
    ticketTypes: [
      {
        name: 'Regular',
        price: 5000,
        quantity: 300,
        tickets: [],
      },
      {
        name: 'VIP',
        price: 20000,
        quantity: 50,
        tickets: [],
      },
    ],
    embeddedVideoUrl: 'https://youtube.com/embed/samplevideo',
    publishedStatus: 'draft',
  },
  {
    _id: '2',
    title: 'Abuja Startup Fair',
    description: 'Connecting startups with investors and mentors.',
    location: 'Abuja International Conference Center',
    city: 'Abuja',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/abuja-startup-fair.jpg',
    coverImageUrl: 'https://example.com/images/abuja-fair-cover.jpg',
    startDateTime: new Date('2025-04-10T10:00:00'),
    endDateTime: new Date('2025-04-10T16:00:00'),
    isFree: true,
    url: 'https://abujastartupfair.ng',
    category: { _id: 'c2', name: 'Business' },
    organizer: { _id: 'o2', firstName: 'Jane', lastName: 'Smith' },
    tags: ['startup', 'business', 'fair'],
    attendeeLimit: 1000,
    ratings: [{ userId: 'u1', rating: 4, comment: 'Great event!' }],
    featured: false,
    ticketTypes: [],
    embeddedVideoUrl: '',
    publishedStatus: 'pending review',
  },
  {
    _id: '3',
    title: 'Port Harcourt Music Festival',
    description:
      'An electrifying music festival in the heart of Port Harcourt.',
    location: 'Port Harcourt Stadium',
    city: 'Port Harcourt',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/ph-music-festival.jpg',
    coverImageUrl: 'https://example.com/images/ph-festival-cover.jpg',
    startDateTime: new Date('2025-05-01T18:00:00'),
    endDateTime: new Date('2025-05-01T23:59:00'),
    isFree: false,
    url: 'https://phmusicfest.ng',
    category: { _id: 'c3', name: 'Music' },
    organizer: { _id: 'o3', firstName: 'Emeka', lastName: 'Okonkwo' },
    tags: ['music', 'festival', 'concert'],
    attendeeLimit: 3000,
    ratings: [],
    featured: true,
    ticketTypes: [
      {
        name: 'General Admission',
        price: 2000,
        quantity: 2500,
        tickets: [],
      },
      {
        name: 'Backstage Pass',
        price: 10000,
        quantity: 50,
        tickets: [],
      },
    ],
    embeddedVideoUrl: 'https://vimeo.com/samplevideo',
    publishedStatus: 'draft',
  },
  {
    _id: '4',
    title: 'Kano Cultural Festival',
    description: 'Experience the vibrant culture and traditions of Kano State.',
    location: 'Kano City Center',
    city: 'Kano',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/kano-cultural-festival.jpg',
    coverImageUrl: 'https://example.com/images/kano-festival-cover.jpg',
    startDateTime: new Date('2025-06-20T10:00:00'),
    endDateTime: new Date('2025-06-20T18:00:00'),
    isFree: true,
    url: 'https://kanoculturalfest.ng',
    category: { _id: 'c4', name: 'Culture' },
    organizer: { _id: 'o4', firstName: 'Amina', lastName: 'Bello' },
    tags: ['culture', 'tradition', 'festival'],
    attendeeLimit: 2000,
    ratings: [],
    featured: false,
    ticketTypes: [],
    embeddedVideoUrl: '',
    publishedStatus: 'pending review',
  },
  {
    _id: '5',
    title: 'Enugu Literary Expo',
    description: 'A gathering of writers, poets, and literature enthusiasts.',
    location: 'Enugu Arts Theater',
    city: 'Enugu',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/enugu-literary-expo.jpg',
    coverImageUrl: 'https://example.com/images/enugu-expo-cover.jpg',
    startDateTime: new Date('2025-07-05T09:00:00'),
    endDateTime: new Date('2025-07-05T17:00:00'),
    isFree: false,
    url: 'https://enugulitexpo.ng',
    category: { _id: 'c5', name: 'Literature' },
    organizer: { _id: 'o5', firstName: 'Chinelo', lastName: 'Okafor' },
    tags: ['literature', 'poetry', 'expo'],
    attendeeLimit: 800,
    ratings: [],
    featured: false,
    ticketTypes: [
      {
        name: 'Regular',
        price: 3000,
        quantity: 500,
        tickets: [],
      },
      {
        name: 'VIP',
        price: 10000,
        quantity: 50,
        tickets: [],
      },
    ],
    embeddedVideoUrl: '',
    publishedStatus: 'draft',
  },
  {
    _id: '6',
    title: 'Calabar Carnival',
    description:
      "Africa's biggest street party featuring colorful parades and performances.",
    location: 'Calabar City',
    city: 'Calabar',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/calabar-carnival.jpg',
    coverImageUrl: 'https://example.com/images/calabar-carnival-cover.jpg',
    startDateTime: new Date('2025-12-01T15:00:00'),
    endDateTime: new Date('2025-12-01T23:00:00'),
    isFree: true,
    url: 'https://calabarcarnival.ng',
    category: { _id: 'c6', name: 'Entertainment' },
    organizer: { _id: 'o6', firstName: 'Ekanem', lastName: 'Bassey' },
    tags: ['carnival', 'parade', 'entertainment'],
    attendeeLimit: 5000,
    ratings: [{ userId: 'u2', rating: 5, comment: 'Best event ever!' }],
    featured: true,
    ticketTypes: [],
    embeddedVideoUrl: 'https://youtube.com/embed/calabarcarnival',
    publishedStatus: 'pending review',
  },
  {
    _id: '7',
    title: 'Calabar Carnival',
    description:
      "Africa's biggest street party featuring colorful parades and performances.",
    location: 'Calabar City',
    city: 'Calabar',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/calabar-carnival.jpg',
    coverImageUrl: 'https://example.com/images/calabar-carnival-cover.jpg',
    startDateTime: new Date('2025-12-01T15:00:00'),
    endDateTime: new Date('2025-12-01T23:00:00'),
    isFree: true,
    url: 'https://calabarcarnival.ng',
    category: { _id: 'c6', name: 'Entertainment' },
    organizer: { _id: 'o6', firstName: 'Ekanem', lastName: 'Bassey' },
    tags: ['carnival', 'parade', 'entertainment'],
    attendeeLimit: 5000,
    ratings: [{ userId: 'u2', rating: 5, comment: 'Best event ever!' }],
    featured: true,
    ticketTypes: [],
    embeddedVideoUrl: 'https://youtube.com/embed/calabarcarnival',
    publishedStatus: 'pending review',
  },
  {
    _id: '7',
    title: 'Calabar Carnival',
    description:
      "Africa's biggest street party featuring colorful parades and performances.",
    location: 'Calabar City',
    city: 'Calabar',
    createdAt: new Date(),
    imageUrl: 'https://example.com/images/calabar-carnival.jpg',
    coverImageUrl: 'https://example.com/images/calabar-carnival-cover.jpg',
    startDateTime: new Date('2025-12-01T15:00:00'),
    endDateTime: new Date('2025-12-01T23:00:00'),
    isFree: true,
    url: 'https://calabarcarnival.ng',
    category: { _id: 'c6', name: 'Entertainment' },
    organizer: { _id: 'o6', firstName: 'Ekanem', lastName: 'Bassey' },
    tags: ['carnival', 'parade', 'entertainment'],
    attendeeLimit: 5000,
    ratings: [{ userId: 'u2', rating: 5, comment: 'Best event ever!' }],
    featured: true,
    ticketTypes: [],
    embeddedVideoUrl: 'https://youtube.com/embed/calabarcarnival',
    publishedStatus: 'pending review',
  },
];

export const nigeriaStates = {
  states: [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'FCT',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
  ],
};
